// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA51yVwSEDy444N5C8_JE4XDvuNX7p3qGE',
    appId: '1:164981521143:web:03357385c41d884a52b1f2',
    messagingSenderId: '164981521143',
    projectId: 'minimalchatapp-74378',
    authDomain: 'minimalchatapp-74378.firebaseapp.com',
    storageBucket: 'minimalchatapp-74378.appspot.com',
    measurementId: 'G-G052MB4ZD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxVy7BeuvUfLfty04lXUIQx7UksrjGFo',
    appId: '1:164981521143:android:c57d7bb6fe821ad652b1f2',
    messagingSenderId: '164981521143',
    projectId: 'minimalchatapp-74378',
    storageBucket: 'minimalchatapp-74378.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSGXnRT4ruitfavDQ1BjQq79-yIadnX4g',
    appId: '1:164981521143:ios:2eea31a2871be84352b1f2',
    messagingSenderId: '164981521143',
    projectId: 'minimalchatapp-74378',
    storageBucket: 'minimalchatapp-74378.appspot.com',
    iosBundleId: 'com.affafistibsharazhar.minimalchatapp',
  );
}
